Add support for uk national insurance numbers
niho/personal-number pull request #3
Opened 2023-08-28 01:51 UTC by Andrew-Clow

2023-08-28 07:48 UTC, niho requested changes
Thank you for your work on this. Much appreciated!

The code looks code and I will merge it and publish it. But I think we need to consider rewriting the documentation a bit first to use a slightly different tone of voice and only include what is relevant for actually using the module. You should also consider removing the hard coded error message strings, as they are not very useful in practice (because of localisation and other UX concerns).

2023-08-28 07:48 UTC, niho commented on .gitignore
> +.idea
You should add this to your global gitignore instead.

https://stackoverflow.com/questions/59328900/how-to-globally-ignore-the-idea-folder-in-git-not-just-adding-it-to-gitignor

2023-08-28 07:48 UTC, niho commented on src/PersonalNumber/UK.elm
> +With apologies to the government website for using an example that they asked me NOT to use,
You should probably refrain from using an informal/personal voice in the documentation. Keep it short, objective and to the point.

2023-08-28 07:48 UTC, niho commented on src/PersonalNumber/UK.elm
> +errorToString e =
This function is not needed and you should probably remove it. Most likely the user of the library will want to customise or localise the error messages, so providing built-in error message strings in not very useful and will encourage bad behaviour (e.g., not thinking about the UX).

You might consider adding a code example to the documentation instead that includes the error message strings from this function. That way a potential user can easily copy paste that code to get started with default error messages.

2023-08-28 07:48 UTC, niho commented on src/PersonalNumber/UK.elm
> +simpleError =
Same goes for this function. It's not needed and should be removed.

2023-08-28 13:10 UTC, Andrew-Clow commented on .gitignore
> +.idea
I use GitHub Desktop, rather than git, and such folders don't exist on my computer, but I have followed this advice to achieve the ignore without hitting the repository:

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#excluding-local-files-without-creating-a-gitignore-file

Summary: `.git/info/exclude` in the local copy has .gitignore functionality but is itself ignored.

2023-08-28 13:17 UTC, Andrew-Clow commented on src/PersonalNumber/UK.elm
> +simpleError =
This hard-coded message string is used anyway as the error message from `decoder : Json.Decode.Decoder NationalInsuranceNumber` and I thought it might be helpful to export it so it could be reused or checked for. 

(I do think that error messages are very much more helpful if they tell you what you should do rather than just "it's wrong". I hate password checkers that only tell you some criteria as you go along - no, it should have more characters, no, still more characters, no, it should have a capital, no it should have a number, no it should have a symbol, no, that symbol isn't allowed, no, it should have a symbol, no that symbol isn't allowed, no, that's too long now.... )

I've unexported it, but of course `decoder` is silently exporting a string anyway.

2023-08-30 07:11 UTC, niho approved these changes

2023-08-30 07:11 UTC, merged